'use strict';
// Setiap soalan: pilihan pertama sederhana, pilihan kedua berlebihan.
// Paparan pilihan diacak pada setiap permainan.
const situations = [
{title:'🍽️ Rumah Terbuka',type:'food',situation:'Aisyah menghadiri rumah terbuka di kawasan kejiranannya. Banyak makanan yang sedap disediakan.',options:['Aisyah mengambil sedikit makanan yang mampu dihabiskannya.','Aisyah mengambil terlalu banyak makanan sehingga banyak makanan tidak habis.'],feedbackCorrect:'Syabas! Aisyah mengambil makanan secukupnya. Ini menunjukkan sikap sederhana dan dapat mengelakkan pembaziran.',feedbackWrong:'Mengambil terlalu banyak makanan boleh menyebabkan pembaziran.',feeling:'Bagaimanakah perasaan kamu apabila mengambil makanan secukupnya?'},
{title:'📱 Masa Menggunakan Gajet',type:'tablet',situation:'Ravi sudah menyiapkan kerja sekolah. Dia mahu bermain permainan menggunakan tablet.',options:['Ravi bermain selama 30 minit dan kemudian melakukan aktiviti lain.','Ravi bermain permainan selama empat jam tanpa berhenti.'],feedbackCorrect:'Bagus! Menggunakan gajet dalam tempoh yang sesuai menunjukkan sikap sederhana.',feedbackWrong:'Bermain terlalu lama merupakan penggunaan gajet secara berlebihan.',feeling:'Bagaimanakah perasaan kamu apabila dapat mengawal masa menggunakan gajet?'},
{title:'🛒 Membeli Barang',type:'shop',situation:'Mei Ling pergi ke kedai bersama keluarganya.',options:['Mei Ling membeli barang yang diperlukan sahaja.','Mei Ling meminta membeli banyak barang kerana tertarik dengan semua barang yang dilihatnya.'],feedbackCorrect:'Tepat! Membeli mengikut keperluan dan kemampuan ialah amalan kesederhanaan.',feedbackWrong:'Membeli terlalu banyak barang yang tidak diperlukan boleh menyebabkan pembaziran.',feeling:'Bagaimanakah perasaan kamu apabila berjaya membeli mengikut keperluan?'},
{title:'🎉 Jamuan Kejiranan',type:'feast',situation:'Kumar menghadiri jamuan bersama penduduk taman.',options:['Kumar makan secukupnya dan berbual dengan jiran-jiran.','Kumar makan terlalu banyak sehingga berasa tidak selesa.'],feedbackCorrect:'Hebat! Menikmati makanan secara sederhana membantu kita menjaga diri dan mengelakkan pembaziran.',feedbackWrong:'Makan terlalu banyak boleh menyebabkan badan berasa tidak selesa.',feeling:'Bagaimanakah perasaan kamu apabila dapat mengawal diri?'},
{title:'💧 Gotong-royong',type:'water',situation:'Penduduk Kampung Harmoni sedang membersihkan kawasan dewan komuniti.',options:['Teck Seng menggunakan air secukupnya untuk membersihkan kawasan.','Teck Seng membiarkan paip terbuka walaupun air tidak digunakan.'],feedbackCorrect:'Bagus! Menggunakan air secukupnya menunjukkan sikap sederhana dan membantu mengelakkan pembaziran.',feedbackWrong:'Membiarkan air mengalir tanpa digunakan merupakan pembaziran.',feeling:'Apakah perasaan kamu apabila berjaya menggunakan sumber dengan baik?'},
{title:'🎊 Menghias Dewan',type:'decor',situation:'Penduduk ingin menghias dewan untuk sambutan perayaan.',options:['Mereka menggunakan hiasan yang mencukupi supaya dewan kelihatan ceria dan kemas.','Mereka membeli terlalu banyak hiasan sehingga memenuhi seluruh dewan dan banyak tidak digunakan.'],feedbackCorrect:'Tepat! Kita boleh meraikan sesuatu dengan gembira tanpa perlu berlebihan.',feedbackWrong:'Hiasan yang terlalu banyak dan tidak digunakan membazirkan wang serta bahan.',feeling:'Bagaimanakah perasaan kamu apabila dapat melakukan sesuatu secara sederhana?'}
];
const app=document.querySelector('#app');let round=0,stars=0,solved=false,emotion='',order=[],answers=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function person(x,y,skin='#be805a',shirt='#448ec0',sad=false){return `<g transform="translate(${x} ${y})"><path d="M-24 72V35Q0 20 24 35V72" fill="${shirt}"/><circle cy="9" r="22" fill="${skin}"/><path d="M-22 8Q-26-22 0-16Q25-19 23 9L12-2-10-3Z" fill="#303737"/><circle cx="-8" cy="9" r="2"/><circle cx="8" cy="9" r="2"/><path d="${sad?'M-7 23Q0 15 7 23':'M-7 18Q0 26 7 18'}" fill="none" stroke="#543a2c" stroke-width="2"/><path d="M-13 73V94M13 73V94" stroke="#324d61" stroke-width="12"/></g>`}
function svg(body){return `<svg viewBox="0 0 420 210" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg">${body}</svg>`}
function art(type,good){let b='<ellipse cx="215" cy="193" rx="185" ry="10" fill="#bccfc0"/>';const skin=type==='tablet'||type==='feast'?'#a86c49':'#dca078';b+=person(65,85,skin,type==='shop'?'#bc658b':'#518cb9',!good&&type==='feast');
if(type==='food'||type==='feast'){b+='<path d="M125 165H380" stroke="#ab7957" stroke-width="14"/><ellipse cx="255" cy="145" rx="83" ry="24" fill="white" stroke="#86a8ae" stroke-width="4"/>';for(let i=0;i<(good?4:18);i++){const x=200+(i%5)*24,y=138-Math.floor(i/5)*21;b+=`<ellipse cx="${x}" cy="${y}" rx="18" ry="13" fill="${['#e9ad52','#7cac67','#db775b'][i%3]}"/>`;}if(type==='feast'&&good)b+=person(353,76,'#d7a17a','#e19a47');if(!good)b+='<path d="M322 177l20 4m-4-13l15 7" stroke="#dd9754" stroke-width="7"/>';}
if(type==='tablet'){b+='<rect x="140" y="73" width="145" height="99" rx="12" fill="#304b65"/><rect x="151" y="83" width="122" height="74" rx="5" fill="#a9d9c8"/><path d="M172 136l27-28 18 14 25-26" stroke="#457c65" stroke-width="7" fill="none"/>';b+=`<rect x="278" y="33" width="129" height="46" rx="12" fill="white"/><text x="343" y="63" text-anchor="middle" font-size="21" fill="#203d48">${good?'30 minit':'4 jam'}</text>`;if(good)b+='<circle cx="338" cy="155" r="25" fill="#e3a451"/><path d="M313 155h50m-25-25v50" stroke="white" stroke-width="3"/>';}
if(type==='shop'){b+='<path d="M144 90h25l20 66h153l24-65H177M195 174h140" fill="none" stroke="#577b80" stroke-width="6"/><circle cx="208" cy="184" r="9" fill="#395968"/><circle cx="328" cy="184" r="9" fill="#395968"/>';for(let i=0;i<(good?3:12);i++)b+=`<rect x="${192+i%4*36}" y="${112-Math.floor(i/4)*33}" width="30" height="36" rx="4" fill="${['#eca963','#679bc1','#bf789b'][i%3]}" stroke="white" stroke-width="2"/>`;}
if(type==='water'){b+='<path d="M309 60v31h-42" fill="none" stroke="#6f8b97" stroke-width="14"/><path d="M294 49h30" stroke="#486574" stroke-width="6"/>';if(good)b+='<path d="M212 120l10 65h58l10-65Z" fill="#64b7d6" stroke="#477889" stroke-width="4"/><path d="M222 119q25-40 55 0" fill="none" stroke="#477889" stroke-width="4"/><path d="M90 140l64 42" stroke="#a07449" stroke-width="7"/><path d="M137 176l33 15" stroke="#b38853" stroke-width="18"/>';else b+='<path d="M266 99v73m9-69v68m-19-62v62" stroke="#57b2d8" stroke-width="6"/><ellipse cx="275" cy="183" rx="97" ry="15" fill="#82cce2"/>';}
if(type==='decor'){b+='<path d="M125 80l130-50 133 50v110H125Z" fill="#eed5ae"/><rect x="229" y="99" width="60" height="91" fill="#84a49f"/>';for(let i=0;i<(good?5:20);i++)b+=`<circle cx="${141+i%7*37}" cy="${72+Math.floor(i/7)*39}" r="13" fill="${['#d58fba','#76b8cf','#e3b952'][i%3]}"/><path d="M${141+i%7*37} ${85+Math.floor(i/7)*39}v17" stroke="#71878c"/>`;if(!good)b+='<rect x="315" y="155" width="70" height="40" fill="#b28657"/><path d="M315 155l30-15 40 15" fill="#cfa16c"/>';}
return svg(b);}
function village(){return `<svg class="village" viewBox="0 0 900 250" aria-hidden="true"><ellipse cx="450" cy="219" rx="420" ry="27" fill="#d4e5c7"/><circle cx="746" cy="47" r="32" fill="#ffdb78"/><path d="M125 125l96-66 96 66v94H125Z" fill="#ebc794"/><path d="M112 127l109-80 109 80" fill="#c66f62"/><rect x="199" y="155" width="44" height="64" fill="#668e8a"/><path d="M558 108l115-75 112 75v111H558Z" fill="#e9d8b0"/><path d="M544 112l129-91 127 91" fill="#558c9a"/><rect x="638" y="147" width="60" height="72" fill="#598d7e"/>${person(367,120,'#d8a076','#619dbc')}${person(428,111,'#a76c48','#e1a657')}${person(489,120,'#efbd94','#c5759b')}${person(550,119,'#ba8158','#69a88d')}<path d="M71 216v-70M823 216v-70" stroke="#98734c" stroke-width="12"/><circle cx="71" cy="119" r="43" fill="#91b986"/><circle cx="823" cy="119" r="43" fill="#91b986"/></svg>`}
function speak(text){const status=document.querySelector('#audio-status');if(!('speechSynthesis'in window)){status.textContent='Audio tidak disokong. Sila baca teks pada skrin.';return;}speechSynthesis.cancel();const voices=speechSynthesis.getVoices();const voice=voices.find(v=>/^ms([-_]|$)/i.test(v.lang));if(!voice){status.textContent='Suara Bahasa Melayu tidak tersedia pada peranti ini. Sila baca teks pada skrin.';return;}const u=new SpeechSynthesisUtterance(text);u.lang='ms-MY';u.voice=voice;u.rate=.85;u.onerror=()=>status.textContent='Audio tidak dapat dimainkan. Sila baca teks pada skrin.';status.textContent='';speechSynthesis.speak(u);}
function show(html){if('speechSynthesis'in window)speechSynthesis.cancel();app.innerHTML=html;const h=app.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus();}window.scrollTo(0,0);}
function menu(){show(`<section class="hero"><p class="tag">Set induksi · Tahun 5 · 5–10 minit</p><h1>Sederhana atau<br>Berlebihan?</h1><p>Jom bantu penduduk Kampung Harmoni membuat pilihan yang sederhana!</p>${village()}<div class="actions"><button class="primary" id="start">▶ Mula Permainan</button><button id="instructions-audio">🔊 Dengar Arahan</button></div><p>Lihat situasi dan pilih tindakan yang menunjukkan sikap sederhana.</p></section>`);document.querySelector('#start').onclick=instructions;document.querySelector('#instructions-audio').onclick=()=>speak('Lihat situasi dan pilih tindakan yang menunjukkan sikap sederhana.');}
function instructions(){show('<section class="panel steps"><p class="tag">Jom bekerjasama</p><h1>Cara bermain</h1><ol><li>Baca atau dengar situasi.</li><li>Lihat dua pilihan tindakan.</li><li>Pilih tindakan yang menunjukkan kesederhanaan.</li><li>Ceritakan perasaan kamu apabila melakukan tindakan tersebut.</li></ol><p>Berbincang bersama. Setiap pusingan, beri rakan lain peluang menyentuh skrin!</p><button class="primary" id="ready">Saya sudah bersedia! 🚀</button></section>');document.querySelector('#ready').onclick=start;}
function start(){round=0;stars=0;answers=[];order=situations.map(()=>Math.random()<.5?[0,1]:[1,0]);renderRound();}
function renderRound(){solved=false;emotion='';const q=situations[round];show(`<div class="status"><span>Situasi ${round+1} / ${situations.length}</span><span class="stars">⭐ ${stars} / ${situations.length}</span></div><progress value="${round}" max="${situations.length}" aria-label="Kemajuan permainan"></progress><section class="question"><h2>${esc(q.title)}</h2><p>${esc(q.situation)}</p><button id="read">🔊 Dengar situasi</button></section><h2>Yang manakah menunjukkan amalan kesederhanaan?</h2><div class="choices">${order[round].map((id,i)=>`<article class="card"><button class="choice" data-id="${id}" aria-label="Pilihan ${i+1}: ${esc(q.options[id])}">${art(q.type,id===0)}<span><b>Pilihan ${i+1}</b><br>${esc(q.options[id])}</span></button><button class="listen" data-read="${id}" aria-label="Dengar pilihan ${i+1}">🔊 Dengar pilihan</button></article>`).join('')}</div><div id="feedback" role="status" aria-live="polite"></div><section id="feelings" class="feelings"></section>`);document.querySelector('#read').onclick=()=>speak(q.situation);app.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>speak(q.options[Number(b.dataset.read)]));app.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.id)));}
function choose(id){if(solved)return;const q=situations[round],fb=document.querySelector('#feedback');fb.className='feedback';if(id!==0){fb.textContent='🤔 Cuba fikir semula. '+q.feedbackWrong+' Adakah tindakan itu dilakukan secara berlebihan?';return;}solved=true;stars++;document.querySelector('.stars').textContent=`⭐ ${stars} / ${situations.length}`;fb.classList.add('success');fb.innerHTML='<b class="burst">⭐ Betul! +1 Bintang Kesederhanaan</b><br>'+esc(q.feedbackCorrect);app.querySelectorAll('[data-id]').forEach(b=>b.disabled=true);document.querySelector('#feelings').innerHTML=`<h2>${esc(q.feeling)}</h2><div class="actions">${[['😊','Gembira'],['😌','Tenang'],['😄','Bangga'],['❤️','Puas hati']].map(([icon,name])=>`<button data-emotion="${name.toLowerCase()}" aria-pressed="false">${icon} ${name}</button>`).join('')}</div><p id="sentence" role="status"></p><button class="primary" id="next" disabled>${round===situations.length-1?'Lihat pencapaian 🏆':'Situasi seterusnya →'}</button>`;app.querySelectorAll('[data-emotion]').forEach(b=>b.onclick=()=>{emotion=b.dataset.emotion;app.querySelectorAll('[data-emotion]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('#sentence').textContent=`Saya berasa ${emotion} kerana saya telah bersikap sederhana.`;document.querySelector('#next').disabled=false;});document.querySelector('#next').onclick=()=>{answers.push(emotion);round++;round<situations.length?renderRound():finish();};document.querySelector('#feelings h2').tabIndex=-1;document.querySelector('#feelings h2').focus();}
function finish(){show(`<section class="panel"><p class="tag">Misi selesai · ${stars} bintang dikumpulkan</p><h1>🎉 Tahniah!</h1><p>Kamu telah menyelesaikan Misi Kesederhanaan!</p><p aria-label="${stars} bintang">${'⭐'.repeat(stars)}</p><h2>Hari ini saya belajar bahawa…</h2><div class="summary">${['🍽️ Ambil makanan secukupnya','📱 Gunakan gajet dalam tempoh yang sesuai','🛒 Beli barang mengikut keperluan','💧 Gunakan air dengan bijak','🎉 Berseronok tanpa berlebihan','❤️ Bersikap sederhana dalam kehidupan bermasyarakat'].map(s=>`<div>${s}</div>`).join('')}</div><p><b>KESEDERHANAAN ialah melakukan sesuatu secara tidak berlebihan dan mengikut keperluan.</b></p><label for="promise">Apakah satu amalan kesederhanaan yang boleh kamu lakukan hari ini?</label><textarea id="promise" maxlength="300" placeholder="Saya akan…"></textarea><p>Kongsikan jawapan kamu dengan rakan dan cuba amalkan hari ini.</p><div class="actions"><button id="replay" class="primary">🔄 Main Semula</button><button id="back">🏠 Kembali ke Menu</button></div></section>`);document.querySelector('#replay').onclick=start;document.querySelector('#back').onclick=menu;}
document.querySelector('#home').onclick=e=>{e.preventDefault();menu();};const dialog=document.querySelector('#teacher-panel');document.querySelector('#teacher').onclick=()=>dialog.showModal();document.querySelector('#close-teacher').onclick=()=>dialog.close();menu();
